//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPP_web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocumentId { get; set; }
        public string Title { get; set; }
        public System.DateTime Date { get; set; }
        public string FilePath { get; set; }
        public int LibarianLibarianId { get; set; }
    
        public virtual Libarian Libarian { get; set; }
    }
}
