//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPP_web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Memo
    {
        public int MemoId { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public int LecturerLecturerId { get; set; }
    
        public virtual Lecturer Lecturer { get; set; }
    }
}
